/**
 * Example authenticated spec — proof-of-life for the storageState fixture.
 *
 * Demonstrates the pattern downstream tests will follow:
 *   1. Import STORAGE_STATE from auth.setup.ts.
 *   2. test.use({ storageState: STORAGE_STATE }) at file scope.
 *   3. Tests can skip the login dance entirely and assert on protected UI.
 *
 * Week-4 RBAC specs will reuse this pattern with per-role storage states
 * (admin.json / operator.json / viewer.json) generated by parallel
 * setup files (admin.setup.ts, operator.setup.ts, viewer.setup.ts).
 */
import { expect, test } from '@playwright/test';
import { STORAGE_STATE } from './auth.setup';

test.use({ storageState: STORAGE_STATE });

test.beforeEach(async ({ context }) => {
  // The fixture runs once at setup time; per-test we still need to honor
  // the same API mocks the auth context depends on, since the storage state
  // only carries cookies + localStorage (not the in-memory route handlers).
  await context.route('**/api/v1/users/profile', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        success: true,
        data: {
          id: 1,
          email: 'e2e@example.com',
          full_name: 'E2E User',
          role: 'admin',
        },
      }),
    });
  });
});

test('lands on the dashboard with the shell mounted', async ({ page }) => {
  await page.goto('/dashboard');

  // Sidebar wordmark is the simplest signal that the shell + auth context
  // both resolved successfully.
  await expect(page.getByText("D'Insight").first()).toBeVisible();

  // The header/sidebar nav surfaces the IA the design audit locked in.
  await expect(page.getByRole('link', { name: /Machine Status/i })).toBeVisible();
  await expect(page.getByRole('link', { name: /Data Ingestion/i })).toBeVisible();
  await expect(page.getByRole('link', { name: /Live Monitor/i })).toBeVisible();
  await expect(page.getByRole('link', { name: /Health Insights/i })).toBeVisible();
  await expect(page.getByRole('link', { name: /Account & Security/i })).toBeVisible();
});
