export const STREAMING_FOCUS_WINDOW_POINTS = 120;
export const STREAMING_MONITORING_EMPHASIS_POINTS = 60;
export const DASHBOARD_STREAMING_TIMELINE_WINDOW = 120;
export const DASHBOARD_IDLE_TIMELINE_WINDOW = 240;
